//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOUSystems
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.CustomerAddresses = new HashSet<CustomerAddress>();
            this.CustomerBrands = new HashSet<CustomerBrand>();
            this.CustomerContactInfoes = new HashSet<CustomerContactInfo>();
            this.CustomerContactPersons = new HashSet<CustomerContactPerson>();
            this.Jobs = new HashSet<Job>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public decimal CreditLimit { get; set; }
        public Nullable<int> CreditPeriod { get; set; }
        public string BusinessRegNo { get; set; }
        public string VatRegNo { get; set; }
        public string NBTRegNo { get; set; }
        public Nullable<System.DateTime> dt_lmd { get; set; }
        public Nullable<int> modify_By { get; set; }
        public string AddressNo { get; set; }
        public string AddressStreet1 { get; set; }
        public string AddressStreet2 { get; set; }
        public string AddressCity { get; set; }
    
        public virtual ICollection<CustomerAddress> CustomerAddresses { get; set; }
        public virtual ICollection<CustomerBrand> CustomerBrands { get; set; }
        public virtual ICollection<CustomerContactInfo> CustomerContactInfoes { get; set; }
        public virtual ICollection<CustomerContactPerson> CustomerContactPersons { get; set; }
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
