//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOUSystems
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerBrand
    {
        public CustomerBrand()
        {
            this.Jobs = new HashSet<Job>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> dt_lmd { get; set; }
        public Nullable<int> modify_By { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
