//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOUSystems
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.AsignedJobs = new HashSet<AsignedJob>();
            this.EmployeeAddresses = new HashSet<EmployeeAddress>();
            this.EmployeeContacts = new HashSet<EmployeeContact>();
            this.Jobs = new HashSet<Job>();
            this.JobsEstimates = new HashSet<JobsEstimate>();
            this.JobsTimeRecodings = new HashSet<JobsTimeRecoding>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string EMPNo { get; set; }
        public string EPFNo { get; set; }
        public string Title { get; set; }
        public string InitialName { get; set; }
        public string SurName { get; set; }
        public string OtherName { get; set; }
        public string NameWithInitial { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string IDnumber { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public Nullable<int> EmployeeTypeID { get; set; }
        public Nullable<decimal> WorkingHours { get; set; }
        public Nullable<decimal> HourlyRate { get; set; }
        public Nullable<System.DateTime> dt_lmd { get; set; }
        public Nullable<int> modify_By { get; set; }
        public Nullable<int> RoleID { get; set; }
    
        public virtual ICollection<AsignedJob> AsignedJobs { get; set; }
        public virtual CompanyRole CompanyRole { get; set; }
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual EmployeeType EmployeeType { get; set; }
        public virtual ICollection<EmployeeAddress> EmployeeAddresses { get; set; }
        public virtual ICollection<EmployeeContact> EmployeeContacts { get; set; }
        public virtual ICollection<Job> Jobs { get; set; }
        public virtual ICollection<JobsEstimate> JobsEstimates { get; set; }
        public virtual ICollection<JobsTimeRecoding> JobsTimeRecodings { get; set; }
    }
}
