//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOUSystems
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeContact
    {
        public int ID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string TelephneNo1 { get; set; }
        public string TelephneNo2 { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string WebLink { get; set; }
        public Nullable<System.DateTime> dt_lmd { get; set; }
        public Nullable<int> modify_By { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
