//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOUSystems
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAddress
    {
        public int ID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string ResidenceNo { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string Street3 { get; set; }
        public string City { get; set; }
        public string Contry { get; set; }
        public string ZibCode { get; set; }
        public Nullable<System.DateTime> dt_lmd { get; set; }
        public Nullable<int> modify_By { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
