//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOUSystems
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.AsignedJobs = new HashSet<AsignedJob>();
            this.JobCostings = new HashSet<JobCosting>();
            this.JobInvoiceDetails = new HashSet<JobInvoiceDetail>();
            this.JobPaymentsDetails = new HashSet<JobPaymentsDetail>();
            this.JobPODetails = new HashSet<JobPODetail>();
            this.JobsEstimates = new HashSet<JobsEstimate>();
            this.JobsTimeRecodings = new HashSet<JobsTimeRecoding>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public string JobNumber { get; set; }
        public string JobDescription { get; set; }
        public string JobType { get; set; }
        public Nullable<int> ProceedBy { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> JobStateID { get; set; }
        public Nullable<System.DateTime> JobActiveDate { get; set; }
        public decimal ToalHoursTaken { get; set; }
        public Nullable<System.DateTime> ActualCloseDate { get; set; }
        public Nullable<System.DateTime> dt_lmd { get; set; }
        public Nullable<int> modify_By { get; set; }
        public Nullable<System.DateTime> JobCreateDate { get; set; }
    
        public virtual ICollection<AsignedJob> AsignedJobs { get; set; }
        public virtual CustomerBrand CustomerBrand { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<JobCosting> JobCostings { get; set; }
        public virtual ICollection<JobInvoiceDetail> JobInvoiceDetails { get; set; }
        public virtual ICollection<JobPaymentsDetail> JobPaymentsDetails { get; set; }
        public virtual ICollection<JobPODetail> JobPODetails { get; set; }
        public virtual jobState jobState { get; set; }
        public virtual ICollection<JobsEstimate> JobsEstimates { get; set; }
        public virtual ICollection<JobsTimeRecoding> JobsTimeRecodings { get; set; }
    }
}
