//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOUSystems
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPaymentsDetail
    {
        public int ID { get; set; }
        public Nullable<int> JobID { get; set; }
        public string ReceiptNumber { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string Method { get; set; }
        public string BankTransferRef { get; set; }
        public string ChequeNumber { get; set; }
        public string ChequeBank { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> POBy { get; set; }
        public Nullable<System.DateTime> dt_lmd { get; set; }
        public Nullable<int> modify_By { get; set; }
        public decimal PaidAmount { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
