//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOUSystems
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobsEstimate
    {
        public int ID { get; set; }
        public Nullable<int> JobID { get; set; }
        public string EstimateNo { get; set; }
        public Nullable<System.DateTime> DateOfEstimate { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public decimal Amount { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> AprovedBy { get; set; }
        public Nullable<System.DateTime> dt_lmd { get; set; }
        public Nullable<int> modify_By { get; set; }
        public decimal CurrancyRate { get; set; }
        public decimal AmountLKR { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Job Job { get; set; }
    }
}
