//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOUSystems
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobsTimeRecoding
    {
        public int ID { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public string Statues { get; set; }
        public Nullable<System.DateTime> DateOfRecord { get; set; }
        public decimal TimeTaken { get; set; }
        public string Coments { get; set; }
        public Nullable<System.DateTime> dt_lmd { get; set; }
        public Nullable<int> modify_By { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Job Job { get; set; }
    }
}
