//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOUSystems
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BBDOIOUEntities : DbContext
    {
        public BBDOIOUEntities()
            : base("name=BBDOIOUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Activity> Activities { get; set; }
        public DbSet<AsignedJob> AsignedJobs { get; set; }
        public DbSet<CompanyRole> CompanyRoles { get; set; }
        public DbSet<CostCategory> CostCategories { get; set; }
        public DbSet<CostElement> CostElements { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Currency> Currencies { get; set; }
        public DbSet<CustomerAddress> CustomerAddresses { get; set; }
        public DbSet<CustomerBrand> CustomerBrands { get; set; }
        public DbSet<CustomerContactInfo> CustomerContactInfoes { get; set; }
        public DbSet<CustomerContactPerson> CustomerContactPersons { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<Designation> Designations { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<EmployeeAddress> EmployeeAddresses { get; set; }
        public DbSet<EmployeeContact> EmployeeContacts { get; set; }
        public DbSet<EmployeeType> EmployeeTypes { get; set; }
        public DbSet<JobCosting> JobCostings { get; set; }
        public DbSet<JobInvoiceDetail> JobInvoiceDetails { get; set; }
        public DbSet<JobPaymentsDetail> JobPaymentsDetails { get; set; }
        public DbSet<JobPODetail> JobPODetails { get; set; }
        public DbSet<Job> Jobs { get; set; }
        public DbSet<JobsEstimate> JobsEstimates { get; set; }
        public DbSet<jobState> jobStates { get; set; }
        public DbSet<JobsTimeRecoding> JobsTimeRecodings { get; set; }
    }
}
